version: '2'
services:
  mydb:
    container_name: mydb_container
    image: postgres
    ports:
      - "5435:5432"
  myweb:
    build: .
    container_name: myweb_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - mydb
